use_frameworks!

platform :ios, '9.0'

target 'JRDNetWork_Example' do
  pod 'JRDNetWork', :path => '../'
  pod 'JRDLogin', :path => '../../JRDLogin'
  target 'JRDNetWork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
