use_frameworks!

platform :ios, '9.0'

target 'JRDLogin_Example' do
  pod 'JRDLogin', :path => '../'

  target 'JRDLogin_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
